# themes are downloaded from: https://github.com/alacritty/alacritty-theme
import = [
  "~/.config/alacritty/themes/themes/tokyo-night.toml",
  "~/.config/alacritty/fonts.toml",
]

[colors]
draw_bold_text_with_bright_colors = true


[env]
TERM = "xterm-256color"


[window]
dynamic_title = true
option_as_alt = "Both"
startup_mode = "Maximized"
opacity = 0.8
dynamic_padding = true
decorations = "Transparent"


[selection]
save_to_clipboard = true

[scrolling]
history = 1000
multiplier = 3

[window.padding]
x = 0
y = 20

[window.class]
general = "Alacritty"
instance = "Alacritty"
